version: '3.2'
services:

  # バージョンごとにサービスを追加する
  # Pytorch 1.10.0
  torch110:

    # Dockerfile の場所
    # コンテキストは torch110 を指定しない
    # （torch110をコンテキストにするとDockerfileで親ディレクトリにある requirements.txt がコピーできない ）
    build:
      context: .  
      dockerfile: torch110/Dockerfile
      
    shm_size: '4gb'
    
    # devcontainer.json で決めたコンテナ名
    container_name: 'container_torch110'

    # コンテナの正常終了を防ぐ（コンテナ側に仮想端末を設置し、コンテナを持続させる）
    tty: true

    # ローカルファイルのマウント
    # 左がローカルファイルの場所, 右がコンテナ上の場所
    volumes: 
      - ../:/work

    # GPUの設定 マウント
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]



